apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xs5z2p2gc-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xs5z2p2gc-go 
  name: xs5z2p2gc-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xs5z2p2gc-go 
